# Copyright (c) 2022, Voltron Data.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-copyright:
    runs-on: ubuntu-latest
    env:
      RAT_JAR: https://repo1.maven.org/maven2/org/apache/rat/apache-rat/0.14/apache-rat-0.14.jar
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Download Rat jar
        run: wget $RAT_JAR -O apache-rat.jar
      - name: Check for copyright/license headers
        run: python ci/check_copyright.py --rat-jar apache-rat.jar

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install package
        run: pip install -e '.[dev]'
      - name: Lint
        run: pre-commit run --all-files

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install package
        run: pip install -e '.[dev]'
      - name: Run tests
        run: pytest --log-level=DEBUG tests
